name       : python-pretend
version    : 1.0.9
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/pretend/pretend-1.0.9.tar.gz : c90eb810cde8ebb06dafcb8796f9a95228ce796531bc806e794c2f4649aa1b10
license    : BSD-3-Clause
component  : programming.python
summary    : Pretend is a library to make stubbing with Python easier
description: |
    Stubbing is a technique for writing tests. You may hear the term mixed up with mocks, fakes, or doubles. Basically a stub is an object that returns pre-canned responses, rather than doing any computation.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
